name: Reset Submodule
on: [workflow_dispatch]
jobs:
reset-submodule:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
   with:
     submodules: recursive
 - name: Reset hbb_common
   run: |
     git submodule deinit -f libs/hbb_common
     rm -rf .git/modules/libs/hbb_common
     git submodule update --init --remote --force libs/hbb_common
 - name: Commit changes
   run: |
     git config user.name "GitHub Actions"
     git config user.email "actions@github.com"
     git add .
     git commit -m "Reset submodule to new fork" || echo "No changes to commit"
     git push
