name: Reset Submodule
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  reset-submodule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
    - name: Reset Submodule
      run: |
        # 1. 解除现有子模块注册
        git submodule deinit -f libs/hbb_common || true
        git rm --cached libs/hbb_common || true
        
        # 2. 彻底删除所有相关文件
        rm -rf .git/modules/libs/hbb_common
        rm -rf libs/hbb_common
        
        # 3. 创建空目录并等待
        mkdir -p libs/hbb_common
        sleep 1  # 确保文件系统更新
        
        # 4. 重新添加子模块
        git submodule add --force https://github.com/zionlio/hbb_common.git libs/hbb_common
        git submodule update --init --remote --force libs/hbb_common

    - name: Commit and push changes
      run: |
        git add .
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Reset submodule to new fork"
          git push origin HEAD:${{ github.ref }}
        fi
