name: Reset Submodule
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  reset-submodule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITHUB_TOKEN }}  # ✅ 保持这样写
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
    - name: Reset Submodule
      run: |
        git submodule deinit -f libs/hbb_common
        git rm --cached libs/hbb_common
        rm -rf .git/modules/libs/hbb_common
        git submodule add --force https://github.com/zionlio/hbb_common.git libs/hbb_common
        git submodule update --init --remote --force libs/hbb_common

    - name: Commit and push changes
      run: |
        git add .
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Reset submodule to new fork"
          # 关键修复：使用正确的引用格式
          git push origin HEAD:refs/heads/${{ github.ref_name }}
        fi
